# Generated by Django 4.2.4 on 2024-02-25 16:57

from django.db import migrations, models
import django.db.models.deletion
import registro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('ci', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('justificacion', models.FileField(blank=True, null=True, upload_to=registro.models.custom_upload_to)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, default=' ', null=True)),
                ('justificacion2', models.FileField(blank=True, null=True, upload_to=registro.models.custom_upload_to)),
                ('fechaSolicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('motivo', models.CharField(choices=[('salud', 'Salud'), ('actividad academica', 'Actividad académica'), ('actividad deportiva/cultural', 'Actividad deportiva/cultural'), ('asunto familiar', 'Asunto familiar'), ('otro', 'Otro')], default='Otro', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_solicitud', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estudiantes')),
            ],
        ),
    ]
