# Generated by Django 4.2.4 on 2024-03-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='materia',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
